# Generated by Django 4.2.4 on 2023-08-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_acg_acg_bool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acg',
            name='acg_follow',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='acg',
            name='acg_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='acg',
            name='acg_progress',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='acg',
            name='acg_second_name',
            field=models.CharField(max_length=50),
        ),
    ]
