# Generated by Django 4.2.4 on 2023-08-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_alter_acg_acg_follow_alter_acg_acg_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acg',
            name='acg_core',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
