# Generated by Django 4.2.4 on 2023-08-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_alter_acg_acg_core'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acg',
            name='acg_core',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
