# Generated by Django 4.2.4 on 2023-08-17 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_alter_acg_acg_core'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_img',
        ),
        migrations.AddField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='../media/23.jpg', upload_to='profile_images'),
        ),
    ]
