# Generated by Django 4.2.4 on 2023-08-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_remove_profile_profile_img_profile_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='23.jpg', upload_to='profile_images'),
        ),
    ]
