# Generated by Django 4.2.4 on 2023-08-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_alter_profile_profileimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_name', models.CharField(max_length=60)),
                ('show_second_name', models.CharField(max_length=50)),
                ('show_url', models.URLField()),
                ('show_follow', models.CharField(max_length=50)),
                ('show_core', models.CharField(blank=True, max_length=50, null=True)),
                ('show_progress', models.CharField(max_length=50)),
                ('show_bool', models.BooleanField(default=True)),
                ('show_img', models.URLField()),
            ],
        ),
    ]
